DROP TABLE IF EXISTS long;

CREATE TABLE long(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) UNIQUE NOT NULL,
  url VARCHAR(2083) NOT NULL,
  topic VARCHAR(200) NOT NULL,
  FULLTEXT search (title, topic )
);

DROP TABLE IF EXISTS long_topics;

CREATE TABLE long_topics(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  topic VARCHAR(255) NOT NULL,
  long_id INT
);
