DROP TABLE IF EXISTS long;

CREATE TABLE long(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) UNIQUE NOT NULL,
  url VARCHAR(2083) NOT NULL,
  topic VARCHAR(200) NOT NULL,
  FULLTEXT search (title, topic)
);
