DROP TABLE IF EXISTS likes_list;

CREATE TABLE likes_list (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  post_id INT NOT NULL,
  liked_by INT NOT NULL
);

DROP TABLE IF EXISTS follows;

CREATE TABLE follows (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  follows INT NOT NULL
);
