DROP TABLE IF EXISTS sessions;

CREATE TABLE sessions (
  sessionID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  token VARCHAR(26) NOT NULL,
  userID INT NOT NULL,
  expiry TIMESTAMP NOT NULL,
  hash VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  hash VARCHAR(255) NOT NULL,
  role VARCHAR(10) NOT NULL,
  last_login VARCHAR(20) NOT NULL,
  display_name VARCHAR(255),
  class VARCHAR(7) NOT NULL,
);
